import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const ubuntu = Ubuntu({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={ubuntu.className}>
                <main className="max-w-4xl mx-auto p-4">{children}</main>
            </body>
        </html>
    );
}
